---
# tasks file for packages

- include: add_yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: add_apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: rem_yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: rem_apt.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: python.yml

